# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
   push:
      branches: [simulation-rebuild]
   pull_request:
      branches: [simulation-rebuild]

jobs:
   dependencies:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [14]
      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v2
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - name: Install
           run: npm ci
         - name: Cache node modules
           uses: actions/cache@v2
           with:
              path: node_modules
              key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
              restore-keys: v1-npm-deps-

   test:
      needs: dependencies
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [14]
      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v2
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - name: Cache node modules
           uses: actions/cache@v2
           with:
              path: node_modules
              key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
         - name: ESLint
           run: npm run eslint:check
         - name: Prettier
           run: npm run prettier:check
         - name: Unit test
           run: npm run test:unit

   build:
      needs: [dependencies, test]
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [14]
      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v2
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - name: Cache node modules
           uses: actions/cache@v2
           with:
              path: node_modules
              key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
         - name: Development build
           run: npm run build:dev
         - name: Development upload
           uses: actions/upload-artifact@v2
           with:
              name: dist-dev
              path: dist-dev
         - name: Production build
           run: npm run build:prod
         - name: Production upload
           uses: actions/upload-artifact@v2
           with:
              name: dist
              path: dist

   deploy:
      needs: [dependencies, test, build]
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [14]
      env:
         CI_PUSH_EMAIL: ${{secrets.CI_PUSH_EMAIL}}
      steps:
         - uses: actions/checkout@v2
         - name: Git configuration
           run: |
              git config --global user.email $CI_PUSH_EMAIL
              git config --global user.name "Opentech UX Github Actions"
         - name: Development download
           uses: actions/download-artifact@v2
           with:
              name: dist-dev
         - name: Production download
           uses: actions/download-artifact@v2
           with:
              name: dist
         - name: Git commands
           run: |
              git checkout -B $GITHUB_REF
              git add --all
         - name: Git push
           run: |
              git commit -m "Build complete [$(date '+%d/%m/%y %T')] [skip actions]"
              git push
