# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
   push:
      branches: [simulation-rebuild]
   pull_request:
      branches: [simulation-rebuild]

jobs:
   dependencies:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [lts]
      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v2
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - run: npm ci

   tests:
      needs: dependencies
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [lts]
      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v2
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - name: lint
         - run: npm run eslint:check
         - name: prettier
         - run: npm run prettier:check
         - name: unit
         - run: npm run test:unit

   build:
      needs: dependencies
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [lts]
      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v2
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - name: Development build
         - run: npm run build:dev
         - name: Production build
         - run: npm run build:prod
